# Loads the providers which load and process the data for validation
providers:
  # Creates a new provider called "terraform" which uses the default terraform provider
  terraform:
    source: default/terraform # use the default terraform provier
    plan: ./plan.json # load the terraform state from ./state.json

policies:
  my-test-policy:
    safeguard: terraform/aws/restrict-resource-types
    provider: terraform
  must-be-terraform-0.12:
    description: Must use Terraform 0.12.0-beta or higher
    safeguard: terraform/version
    provider: terraform
    settings:
      range: "^0.13.0-beta"