# Loads the providers which load and process the data for validation
providers:
  # Creates a new provider called "terraform" which uses the default terraform provider
  terraform:
    source: default/terraform # use the default terraform provier
    state: ./state.json # load the terraform state from ./state.json

policies:
  my-test-policy:
    safeguard: terraform/restrict-resource-types
    provider: terraform
  must-be-terraform-0.12:
    safeguard: terraform/version
    provider: terraform
    settings:
      range: "^0.12.0-beta"