providers:
- source: default/terraform

policies:
  my-test-policy:
    safeguard: terraform/aws/restrict-resource-types
  min-version:
    safeguard: terraform/version
    settings:
      range: "^0.12.0-beta"