providers:
  terraform:
    source: default/terraform # use the default terraform provier
    # The `plan` field is optionl. If `plan` isn't set, the provider will run `terraform plan` and
    # `terraform show` to generate.
    # plan: ./plan.json 

policies:
  my-test-policy:
    safeguard: terraform/aws/restrict-resource-types
    provider: terraform
  must-be-terraform-0.12:
    description: Must use Terraform 0.12.0-beta or higher
    safeguard: terraform/version
    provider: terraform
    settings:
      range: "^0.13.0-beta"